# Reffer to https://golangci-lint.run/usage/configuration/ for documentation
# run:
#   tests: false
output:
  sort-results: true
# linters-settings:
#   revive:
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
issues:
  # To list all excluded by default patterns execute `golangci-lint run --help`.
  exclude-use-default: false
  # default: 50
  max-issues-per-linter: 0
  # deafult: 3 of the same warning messages
  max-same-issues: 0
  